# Generated by Django 3.1.5 on 2021-04-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_lst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, null=True)),
                ('fname', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock_lst')),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stocks.user')),
            ],
        ),
    ]
