# Generated by Django 3.1.5 on 2021-04-02 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_favourite_stock_lst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
    ]
