# Generated by Django 3.1.5 on 2021-04-03 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210402_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock_lst'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.account'),
        ),
    ]
