# Generated by Django 3.1.5 on 2021-05-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20210511_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='stock',
        ),
        migrations.AddField(
            model_name='favourite',
            name='ticker',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
