# Generated by Django 3.1.5 on 2021-05-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_auto_20210511_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, null=True)),
                ('ticker', models.CharField(max_length=20, null=True)),
                ('fname', models.CharField(max_length=30, null=True)),
                ('open', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('volume', models.IntegerField(null=True)),
            ],
        ),
    ]
